# ConfigMap chứa các biến môi trường công khai cho Frontend
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  # Địa chỉ API công cộng mới (Public IP đã được cấp)
  # Sử dụng HTTPS với subdomain riêng cho API
  VITE_API_BASE_URL: "https://api.vuonghn.mindx.com.vn"
  
  # Các khóa Firebase PUBLIC
  VITE_FIREBASE_API_KEY: "AIzaSyBV1ljVpG7E8h6Age_bj8K_6LzMZSLMzXA"
  VITE_FIREBASE_AUTH_DOMAIN: "backendlogin-d658e.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "backendlogin-d658e"
  VITE_FIREBASE_APP_ID: "1:674340718429:web:cc4712c6de6a7e65440ab4"